### PR TITLE
Update Azure Storage Emulator

### PR DESCRIPTION
**Pull request by Megasware128**

### CODE REVIEW

**Comment by tg123** [comment]
AFAIK
storage emulator deprecated and moved to https://github.com/azure/azurite
this is why this repo stop push update to docker hub

**Comment by Megasware128** [comment]
I get that. I was still using this because of the missing table support

**Comment by Megasware128** [comment]
You may close this if you think it is unnecessary. I've updated Storage Emulator so I can run Durable Azure Functions isolated

**Comment by tg123** [comment]
Merge but I want to let you know this one is replaced by azurite and will not sync to docker hub anymore.

**Pull request merged**
